/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    PlantManage: typeof import('./src/components/plant-manage/index.vue')['default']
    PlantManagement: typeof import('./src/components/plant-management/index.vue')['default']
    SeedsStorehouse: typeof import('./src/components/seeds-storehouse/index.vue')['default']
  }
}
